-- Biblio — SEED del menu da src/data/menu.ts (generato da scripts/gen-menu-seed.mjs).
-- Esegui DOPO 0001_init.sql. Idempotente: popola solo se le tabelle sono vuote,
-- così non sovrascrive le modifiche fatte dal proprietario nella dashboard.

do $$
begin
  if not exists (select 1 from public.menu_sections) then

    insert into public.menu_sections
      (id, chapter_id, chapter_title_it, chapter_title_en, chapter_intro_it, chapter_intro_en,
       title_it, title_en, intro_it, intro_en, default_price, render_as, sort_index)
    values
  ('vini-bianchi', 'bevande', 'Le nostre bevande', 'Wines, beers & sodas', 'Vini di territorio, birre artigianali alla spina e bibite italiane di carattere. La base ampia che accompagna la sera, dalla cena al concerto.', 'Wines from the territory, craft beers on tap and characterful Italian sodas. The everyday backbone of the evening, from dinner through the live set.', 'Vini bianchi', 'White wines', null, null, '5', 'rows', 0),
  ('vini-rossi', 'bevande', 'Le nostre bevande', 'Wines, beers & sodas', 'Vini di territorio, birre artigianali alla spina e bibite italiane di carattere. La base ampia che accompagna la sera, dalla cena al concerto.', 'Wines from the territory, craft beers on tap and characterful Italian sodas. The everyday backbone of the evening, from dinner through the live set.', 'Vini rossi', 'Red wines', null, null, '5', 'rows', 1),
  ('bollicine', 'bevande', 'Le nostre bevande', 'Wines, beers & sodas', 'Vini di territorio, birre artigianali alla spina e bibite italiane di carattere. La base ampia che accompagna la sera, dalla cena al concerto.', 'Wines from the territory, craft beers on tap and characterful Italian sodas. The everyday backbone of the evening, from dinner through the live set.', 'Bollicine', 'Sparkling', null, null, null, 'rows', 2),
  ('birre-spina', 'bevande', 'Le nostre bevande', 'Wines, beers & sodas', 'Vini di territorio, birre artigianali alla spina e bibite italiane di carattere. La base ampia che accompagna la sera, dalla cena al concerto.', 'Wines from the territory, craft beers on tap and characterful Italian sodas. The everyday backbone of the evening, from dinner through the live set.', 'Birre Baroh, alla spina', 'Baroh beers, on tap', null, null, null, 'rows', 3),
  ('birre-bottiglia', 'bevande', 'Le nostre bevande', 'Wines, beers & sodas', 'Vini di territorio, birre artigianali alla spina e bibite italiane di carattere. La base ampia che accompagna la sera, dalla cena al concerto.', 'Wines from the territory, craft beers on tap and characterful Italian sodas. The everyday backbone of the evening, from dinner through the live set.', 'Birre in bottiglia 0.5 L', 'Bottled beers 0.5 L', null, null, '8', 'rows', 4),
  ('bibite', 'bevande', 'Le nostre bevande', 'Wines, beers & sodas', 'Vini di territorio, birre artigianali alla spina e bibite italiane di carattere. La base ampia che accompagna la sera, dalla cena al concerto.', 'Wines from the territory, craft beers on tap and characterful Italian sodas. The everyday backbone of the evening, from dinner through the live set.', 'Bibite Cortese', 'Cortese sodas', null, null, '4', 'rows', 5),
  ('negroni-gin', 'negroni', 'I nostri Negroni', 'Our Negronis', 'Dal 1919, il bilanciamento tra amaro e vermouth ha reso il Negroni il cocktail italiano per eccellenza. In questo menù celebriamo la straordinaria flessibilità della sua ricetta: una struttura immutata che cambia anima a seconda del distillato principale.', 'Since 1919 the balance between bitter and vermouth has made the Negroni the quintessential Italian cocktail. Here we celebrate the recipe’s remarkable flexibility, an unchanged structure whose soul shifts with the spirit at its core.', 'Con gin', 'With gin', 'La forma originaria del Negroni, spinta verso le possibilità di oggi. La spina dorsale di ginepro viene declinata attraverso la varietà della distillazione contemporanea.', 'The original Negroni, pushed into today’s possibilities. The juniper backbone is reread through the breadth of contemporary distillation.', '10', 'items', 6),
  ('negroni-whisky', 'negroni', 'I nostri Negroni', 'Our Negronis', 'Dal 1919, il bilanciamento tra amaro e vermouth ha reso il Negroni il cocktail italiano per eccellenza. In questo menù celebriamo la straordinaria flessibilità della sua ricetta: una struttura immutata che cambia anima a seconda del distillato principale.', 'Since 1919 the balance between bitter and vermouth has made the Negroni the quintessential Italian cocktail. Here we celebrate the recipe’s remarkable flexibility, an unchanged structure whose soul shifts with the spirit at its core.', 'Con whisky', 'With whisky', 'Nato nei bar parigini durante il proibizionismo, il Boulevardier dimostra come il whisky sappia reinventare il classico italiano vestendolo con sentori caldi e legnosi.', 'Born in Paris bars during Prohibition, the Boulevardier shows how whisky can rework the Italian classic, dressing it in warm, woody notes.', '10', 'items', 7),
  ('negroni-mezcal', 'negroni', 'I nostri Negroni', 'Our Negronis', 'Dal 1919, il bilanciamento tra amaro e vermouth ha reso il Negroni il cocktail italiano per eccellenza. In questo menù celebriamo la straordinaria flessibilità della sua ricetta: una struttura immutata che cambia anima a seconda del distillato principale.', 'Since 1919 the balance between bitter and vermouth has made the Negroni the quintessential Italian cocktail. Here we celebrate the recipe’s remarkable flexibility, an unchanged structure whose soul shifts with the spirit at its core.', 'Con mezcal', 'With mezcal', 'L’incontro perfetto fra l’agave messicana e l’amaro italiano. Figlio della moderna evoluzione del bar, il Mezcal Negroni sostituisce le classiche botaniche del gin con sentori rustici, vegetali e affumicati del distillato artigianale.', 'The perfect meeting of Mexican agave and Italian amaro. A child of the modern bar, the Mezcal Negroni replaces the classic gin botanicals with rustic, vegetal, smoky notes from the artisanal spirit.', '10', 'items', 8),
  ('negroni-rum', 'negroni', 'I nostri Negroni', 'Our Negronis', 'Dal 1919, il bilanciamento tra amaro e vermouth ha reso il Negroni il cocktail italiano per eccellenza. In questo menù celebriamo la straordinaria flessibilità della sua ricetta: una struttura immutata che cambia anima a seconda del distillato principale.', 'Since 1919 the balance between bitter and vermouth has made the Negroni the quintessential Italian cocktail. Here we celebrate the recipe’s remarkable flexibility, an unchanged structure whose soul shifts with the spirit at its core.', 'Con rum', 'With rum', 'Un classico moderno che unisce la struttura italiana alla complessità dei distillati di canna da zucchero. Il rum prende il posto del gin per regalare al Negroni inaspettate note di melassa, spezie e legno.', 'A modern classic uniting Italian structure with the complexity of cane spirits. Rum takes the place of gin to give the Negroni unexpected notes of molasses, spice and wood.', '10', 'items', 9),
  ('americani-list', 'americani', 'I nostri Americani', 'Our Americanos', 'L’evoluzione del Milano-Torino che ha fatto la storia a cavallo del Novecento. La semplicità dell’Americano viene reinterpretata attraverso bitter moderni e vermouth di carattere, per scoprire ogni possibile declinazione dell’aperitivo.', 'The evolution of the Milano-Torino that shaped a century of Italian aperitivo. The simplicity of the Americano is rewritten through modern bitters and characterful vermouth, exploring every possible reading of the cocktail.', 'Il menù', 'The list', null, null, '8', 'items', 10),
  ('gin-tonic-list', 'gin-tonic', 'Gin & Tonic', 'Gin & Tonic', 'Il classico britannico per eccellenza, nato come cura e diventato un rito. Una ricerca minuziosa dell’incontro tra gin internazionali, toniche premium e guarnizioni specifiche, per trasformare due soli ingredienti in un’esperienza di degustazione.', 'The quintessential British classic, born as a cure and turned into a ritual. A careful pairing of international gins, premium tonics and specific garnishes, turning two ingredients into a tasting experience.', 'La selezione', 'The selection', null, null, null, 'items', 11),
  ('cucina-list', 'cucina', 'I nostri piatti', 'Our plates', 'Cicchetti gourmet pensati per accompagnare la musica e non interrompere la conversazione. Materie prime italiane, pochi piatti, ognuno con un’identità precisa.', 'Gourmet small plates built to ride alongside the music and not interrupt the conversation. Italian ingredients, a short list, each plate with a clear identity.', 'Il menù', 'The list', null, null, '15', 'items', 12);

    insert into public.menu_items
      (section_id, name, origin, profile_it, profile_en, desc_it, desc_en, price, sort_index)
    values
  ('vini-bianchi', 'Friulano', null, null, null, null, null, null, 0),
  ('vini-bianchi', 'Gewurztraminer', null, null, null, null, null, null, 1),
  ('vini-bianchi', 'Ribolla', null, null, null, null, null, null, 2),
  ('vini-rossi', 'Pinot Nero', null, null, null, null, null, null, 0),
  ('vini-rossi', 'Valpolicella Ripasso', null, null, null, null, null, null, 1),
  ('vini-rossi', 'Carmenere', null, null, null, null, null, null, 2),
  ('bollicine', 'Prosecco Brut', null, null, null, null, null, '4', 0),
  ('bollicine', 'Trento Doc', null, null, null, null, null, '6', 1),
  ('birre-spina', 'Bionda 0.2 L', null, null, null, null, null, '3', 0),
  ('birre-spina', 'Bionda 0.4 L', null, null, null, null, null, '6', 1),
  ('birre-spina', 'IPA 0.2 L', null, null, null, null, null, '4', 2),
  ('birre-spina', 'IPA 0.4 L', null, null, null, null, null, '7', 3),
  ('birre-bottiglia', 'Bianca', null, null, null, null, null, null, 0),
  ('birre-bottiglia', 'Session IPA', null, null, null, null, null, null, 1),
  ('birre-bottiglia', 'Rossa', null, null, null, null, null, null, 2),
  ('birre-bottiglia', 'Nera', null, null, null, null, null, null, 3),
  ('bibite', 'Arancia Rossa', null, null, null, null, null, null, 0),
  ('bibite', 'Chinotto', null, null, null, null, null, null, 1),
  ('bibite', 'Cedrata', null, null, null, null, null, null, 2),
  ('bibite', 'Cortesino', null, null, null, null, null, null, 3),
  ('bibite', 'Lemon', null, null, null, null, null, null, 4),
  ('bibite', 'Soda Pompelmo', null, null, null, null, null, null, 5),
  ('bibite', 'Ginger Beer', null, null, null, null, null, null, 6),
  ('negroni-gin', 'Perfect Three', null, null, null, 'L’espressione più bilanciata: note pungenti del ginepro, sostenute da una ricca dolcezza vanigliata.', 'The most balanced expression, pungent juniper notes carried by a rich vanilla sweetness.', null, 0),
  ('negroni-gin', 'Contessa', null, null, null, 'Raffinato e setoso, unisce la struttura di un gin tradizionale a sfumature dolci e morbidamente floreali.', 'Refined and silky, blending the frame of a traditional gin with soft, floral, sweet shades.', null, 1),
  ('negroni-gin', 'Austero', null, null, null, 'Imponente e senza compromessi: la gradazione elevata esalta una struttura scura, amara e tostata.', 'Bold and uncompromising, high proof draws out a dark, bitter, toasted structure.', null, 2),
  ('negroni-gin', 'Tropicale', null, null, null, 'Floreale e avvolgente, con sentori botanici esotici che si fondono a una base ricca ma vellutata.', 'Floral and enveloping, with exotic botanicals melting into a rich yet velvety base.', null, 3),
  ('negroni-gin', 'Via della Seta', null, null, null, 'Esotico e speziato, unisce sentori orientali di citronella a un cuore erbaceo artigianale.', 'Exotic and spiced, weaving Eastern lemongrass into an artisanal herbal heart.', null, 4),
  ('negroni-gin', 'Clandestino', null, null, null, 'Un trionfo di erbe e resine artigianali: un sorso profondo e complesso, unico nel suo genere.', 'A triumph of artisanal herbs and resins, deep, complex, one of a kind.', null, 5),
  ('negroni-gin', 'Soprano', null, null, null, 'Verticale e tagliente: il ginepro svetta sull’intensità del bitter e sul rigore del Vermouth dry.', 'Vertical and sharp, juniper rising over bitter intensity and the rigour of dry Vermouth.', null, 6),
  ('negroni-gin', 'Tokyo Zen', null, null, null, 'Limpido e meditativo, un sorso estremamente leggero con un delicato sentore vegetale.', 'Clean and meditative, an exceptionally light sip with a delicate vegetal hint.', null, 7),
  ('negroni-gin', 'Kyoto Flower', null, null, null, 'Delicato e floreale: il fiore di ciliegio fa da protagonista su un sorso rotondo e morbido.', 'Delicate and floral, cherry blossom takes the lead over a round, soft sip.', null, 8),
  ('negroni-gin', 'Boschivo', null, null, null, 'Balsamico e profumato, con sfumature montane che si fondono in un sorso fresco.', 'Balsamic and fragrant, with mountain shades melting into a fresh, clean sip.', null, 9),
  ('negroni-whisky', 'Grand Soir', null, null, null, 'Caldo e legnoso: le note di caramello e rovere del whiskey abbracciano la classica struttura dolce-amara.', 'Warm and woody, caramel and oak from whiskey wrap around the classic bittersweet frame.', null, 0),
  ('negroni-whisky', 'Revolution', null, null, null, 'Oscuro e ribelle: la nota torbata dello scotch si lega al fondo scuro in un sorso profondo e terroso.', 'Dark and rebellious, peated scotch ties into the dark base for a deep, earthy sip.', null, 1),
  ('negroni-whisky', 'Golden Age', null, null, null, 'Morbido e dorato: la rotondità del bourbon si siede su un profilo dolce-amaro limpido e leggero.', 'Soft and golden, the round body of bourbon settles on a clean, light bittersweet profile.', null, 2),
  ('negroni-mezcal', 'Rojo', null, null, null, 'Affumicato e terroso: il carattere rustico dell’agave si sposa con profumi erbacei, ricchi e tradizionali.', 'Smoky and earthy, the rustic character of agave marries rich, traditional herbal aromas.', null, 0),
  ('negroni-mezcal', 'Dorado', null, null, null, 'Fumoso e avvolgente: calde note speziate si fondono a sentori terrosi, un sorso intenso e persistente.', 'Smoky and enveloping, warm spiced notes meet earthy hints in an intense, persistent sip.', null, 1),
  ('negroni-mezcal', 'Bianco', null, null, null, 'Luminoso e vibrante: sfumature erbacee incontrano una spinta minerale, per un sorso fumoso e asciutto.', 'Bright and vibrant, herbal shades meet a mineral push for a smoky, dry sip.', null, 2),
  ('negroni-rum', 'Brisa', null, null, null, 'Trasparente e puro ma sorprendentemente complesso: fresco, floreale, vivace e dissetante.', 'Clear and pure yet surprisingly complex, fresh, floral, lively and thirst-quenching.', null, 0),
  ('negroni-rum', 'Solera', null, null, null, 'Profondo e suadente, dominato da note di melassa, legno tostato e frutta matura: un sorso pieno.', 'Deep and persuasive, led by molasses, toasted wood and ripe fruit, a full-bodied sip.', null, 1),
  ('negroni-rum', 'Siesta', null, null, null, 'Limpido e dorato ma avvolgente e caldo: amabile, meditativo, rilassante e irresistibile.', 'Clear and golden yet warm and enveloping, easy-going, meditative, relaxing, irresistible.', null, 2),
  ('americani-list', 'Opulento', null, null, null, 'Ricco e complesso: spiccano eleganti sentori di vaniglia, spezie e frutta secca che donano rotondità.', 'Rich and complex, elegant notes of vanilla, spice and dried fruit lend roundness.', null, 0),
  ('americani-list', 'Tradizionale', null, null, null, 'Autentico e fortemente legato al territorio piemontese: sprigiona note erbacee, calde e speziate.', 'Authentic and rooted in Piedmont, herbal, warm, spiced notes throughout.', null, 1),
  ('americani-list', 'Balsamico', null, null, null, 'Estremamente aromatico, dominato da sentori di erbe officinali e resine artigianali.', 'Highly aromatic, led by medicinal herbs and artisanal resins.', null, 2),
  ('americani-list', 'Radicale', null, null, null, 'Scuro, intenso e terroso, con spiccate note di china, rabarbaro e un forte retrogusto amaro.', 'Dark, intense and earthy, with pronounced cinchona, rhubarb and a strong bitter finish.', null, 3),
  ('americani-list', 'Ambrato', null, null, null, 'Morbido ed elegante: accarezza il palato con note agrumate e speziate sottili e un finale setoso.', 'Soft and elegant, citrus and subtle spice graze the palate with a silky finish.', null, 4),
  ('americani-list', 'Rosato', null, null, null, 'Fresco, fruttato e amichevole: combina profumi delicati con un tocco di Americano beverino.', 'Fresh, fruity and friendly, delicate aromatics meet an easy-drinking Americano touch.', null, 5),
  ('americani-list', 'Candido', null, null, null, 'Delicato e rinfrescante, si distingue per la limpidezza e per le eleganti sfumature dolci.', 'Delicate and refreshing, clean, with elegantly sweet shades.', null, 6),
  ('americani-list', 'Secco', null, null, null, 'Nitido e affilato: unisce la nota vinosa secca del vermouth dry alle sfumature agrumate e dolci.', 'Crisp and sharp, the dry, wine-like vermouth meets citrus and sweet shades.', null, 7),
  ('americani-list', 'Onesto', null, null, null, 'Diretto e senza compromessi: l’intensità del bitter incontra la finezza del vermouth dry.', 'Direct and uncompromising, bitter intensity meets the finesse of dry vermouth.', null, 8),
  ('americani-list', 'Bianco-cano', null, null, null, 'Inaspettato e dissetante, si bilancia fra vermouth bianco, bitter e la freschezza luppolata della pilsner.', 'Unexpected and refreshing, balanced between white vermouth, bitter and the hoppy lift of pilsner.', null, 9),
  ('americani-list', 'IPA-cano', null, null, null, 'Frizzante, agrumato e luppolato: unisce l’amarezza tipica dell’aperitivo al tocco pungente della birra IPA.', 'Sparkling, citrus-driven and hoppy, classic aperitivo bitterness meets the bite of an IPA.', null, 10),
  ('gin-tonic-list', 'No. 3', '(UK)', 'Secco, citrico, tagliente', 'Dry, citric, sharp', null, null, '10', 0),
  ('gin-tonic-list', '50 Pounds', '(UK)', 'Secco, morbido, elegante', 'Dry, soft, elegant', null, null, '10', 1),
  ('gin-tonic-list', 'Hayman’s Royal Dock', '(UK)', 'Secco, alcolico, pungente', 'Dry, high-proof, pungent', null, null, '10', 2),
  ('gin-tonic-list', 'Junipero', '(USA)', 'Secco, intenso, pungente', 'Dry, intense, pungent', null, null, '12', 3),
  ('gin-tonic-list', 'Roku', '(Giappone)', 'Secco, pepato, setoso', 'Dry, peppery, silky', null, null, '10', 4),
  ('gin-tonic-list', 'Ukiyo Yuzu', '(Giappone)', 'Agrumato, acidulo, fresco', 'Citric, tart, fresh', null, null, '12', 5),
  ('gin-tonic-list', 'Marconi 42', '(Italia, Veneto)', 'Mediterraneo, erbaceo, balsamico', 'Mediterranean, herbal, balsamic', null, null, '10', 6),
  ('gin-tonic-list', 'Clandestino', '(Italia, Emilia)', 'Aromatico, resinoso, speziato', 'Aromatic, resinous, spiced', null, null, '10', 7),
  ('gin-tonic-list', 'Ukiyo Blossom', '(Giappone)', 'Morbido, floreale, fresco', 'Soft, floral, fresh', null, null, '12', 8),
  ('gin-tonic-list', 'Mellifera', '(Francia)', 'Floreale, balsamico, setoso', 'Floral, balsamic, silky', null, null, '10', 9),
  ('gin-tonic-list', 'Bobby’s', '(Olanda)', 'Speziato, fresco, secco', 'Spiced, fresh, dry', null, null, '10', 10),
  ('gin-tonic-list', 'Elephant', '(Germania)', 'Terroso, erbaceo, strutturato', 'Earthy, herbal, structured', null, null, '12', 11),
  ('gin-tonic-list', 'Sahena', '(Thailandia)', 'Fruttato, speziato, esotico', 'Fruity, spiced, exotic', null, null, '12', 12),
  ('gin-tonic-list', 'Crafter’s Wild Forest', '(Estonia)', 'Boschivo, resinoso, fresco', 'Forest, resinous, fresh', null, null, '12', 13),
  ('gin-tonic-list', 'Old Man Project 3', '(Germania)', 'Fruttato, morbido, vivace', 'Fruity, soft, lively', null, null, '12', 14),
  ('cucina-list', 'Tartare di Fassona', null, null, null, 'Con stracciatella artigianale e granella di pistacchi.', 'With artisanal stracciatella and pistachio crumble.', null, 0),
  ('cucina-list', 'Carpaccio di Black Angus', null, null, null, 'Su letto di valeriana con chutney all’albicocca.', 'On a bed of lamb’s lettuce with apricot chutney.', null, 1),
  ('cucina-list', 'Tagliata di Pollo', null, null, null, 'Sous vide e affumicata, con patate al forno e salsa allo yogurt.', 'Sous vide and smoked, with roast potatoes and yoghurt sauce.', '18', 2),
  ('cucina-list', 'Carpaccio di Pesce Spada', null, null, null, 'Affumicato, su letto di valeriana con chutney di mango.', 'Smoked, on a bed of lamb’s lettuce with mango chutney.', '18', 3),
  ('cucina-list', 'Carpaccio di Tonno', null, null, null, 'Affumicato, su letto di valeriana con chutney al fico.', 'Smoked, on a bed of lamb’s lettuce with fig chutney.', '18', 4),
  ('cucina-list', 'Gazpacho', null, null, null, 'Con burrata artigianale e alici del Mar Cantabrico.', 'With artisanal burrata and Cantabrian anchovies.', '16', 5),
  ('cucina-list', 'Hummus e Friarielli', null, null, null, 'Hummus di ceci, friarielli napoletani e pomodorini semi-secchi.', 'Chickpea hummus, Neapolitan friarielli greens and semi-dried cherry tomatoes.', null, 6);

  end if;
end $$;
